name: Deploy Application

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    container:
      image: node:20
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}